"""
Guest fixup K8s Job — runs virt-customize on a qcow2 in place.

Strategy:
    Mount the transit NFS export RW on the pod (same SCC as populator,
    nfs volume allowed via shiftwise-populator SCC). Run a self-contained
    bash script that:
        1. Drops a generic DHCP config matching all common virtio NIC names
           (covers ifupdown, systemd-networkd, NetworkManager — whichever
           the guest uses, only one will pick it up).
        2. Enables ``serial-getty@ttyS0`` so KubeVirt's ``virtctl console``
           works.
        3. Patches GRUB to send kernel boot logs to ttyS0 too.
        4. SELinux relabel.

Idempotent — running twice on the same disk is safe (writes overwrite,
systemctl enable is no-op if already enabled).

KVM acceleration:
    libguestfs uses ``/dev/kvm`` if available (privileged + KVM device
    plugin on the node). Otherwise it falls back to TCG which is 5–10×
    slower. We try privileged first; if the cluster admin has not enabled
    KVM, we still finish (just slowly). The Job is privileged because
    /dev/kvm requires it on OpenShift 4.18 by default.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass
from typing import Optional

from kubernetes.client.rest import ApiException

from app.core.config import settings
from app.core.kubevirt_client import get_kubevirt_client
from app.services.adapter.errors import AdapterError

logger = logging.getLogger(__name__)


_LABEL_APP = "app.shiftwise.io/component"
_LABEL_APP_VAL = "adapter"
_LABEL_MIGRATION = "app.shiftwise.io/migration-id"
_LABEL_DISK = "app.shiftwise.io/disk-index"


# The fixup script. Embedded here rather than as a ConfigMap because:
#   1. It's small (< 4 KiB).
#   2. Versioning happens in the Python source — every code change
#      bumps the script atomically with the orchestrator that uses it.
#   3. No extra ConfigMap to manage in tenant namespaces.
#
# All operations are idempotent and use ``|| true`` to survive missing
# files (GRUB on Ubuntu vs grub2 on RHEL, etc.).
_FIXUP_SCRIPT = r"""#!/bin/bash
set -eu
DISK="${DISK_PATH:?missing DISK_PATH}"

echo ">>> Adapter starting on $DISK"
ls -la "$DISK"

# OpenShift assigne une UID différente par namespace. Le qcow2 a été écrit
# par le converter dans le namespace `shiftwise` (UID 1000760000) alors que
# l'adapter tourne dans le namespace tenant `shiftwise-{tenant}` (UID
# 1000790000). Sans les permissions group-write, qemu refuse d'ouvrir le
# fichier en RW. Chmod 0666 explicite — la donnée est sur un partage NFS
# interne au cluster, accessible uniquement aux SAs autorisés.
chmod 0666 "$DISK" || {
  echo "WARN: chmod failed (file probably read-only on NFS); continuing"
}
ls -la "$DISK"

mkdir -p /tmp/cfg

# systemd-networkd: matches every virtio interface name pattern at once.
cat > /tmp/cfg/networkd.network <<'EOF'
[Match]
Name=en* eth*
[Network]
DHCP=yes
EOF

# ifupdown (Debian default with /etc/network/interfaces).
# We list every realistic virtio name; missing interfaces are silently
# skipped by ifup.
cat > /tmp/cfg/ifupdown.cfg <<'EOF'
# Auto-generated by ShiftWise Adapter — DHCP on any common virtio NIC name.
auto enp1s0
iface enp1s0 inet dhcp

auto enp2s0
iface enp2s0 inet dhcp

auto ens2
iface ens2 inet dhcp

auto ens3
iface ens3 inet dhcp

auto eth0
iface eth0 inet dhcp
EOF

# NetworkManager keyfile (RHEL/Fedora/Ubuntu default).
cat > /tmp/cfg/nm.nmconnection <<'EOF'
[connection]
id=shiftwise-dhcp
type=ethernet
autoconnect=true
[ipv4]
method=auto
[ipv6]
method=auto
EOF

# netplan (Ubuntu 18+).
cat > /tmp/cfg/netplan.yaml <<'EOF'
network:
  version: 2
  ethernets:
    all-en:
      match: {name: "en*"}
      dhcp4: true
      dhcp6: true
    all-eth:
      match: {name: "eth*"}
      dhcp4: true
EOF

echo ">>> Running virt-customize"
# --mkdir avant chaque --upload : les dossiers /etc/NetworkManager,
# /etc/systemd/network, /etc/netplan n'existent que si la stack
# correspondante est installée. virt-customize --upload ne crée pas le
# parent automatiquement. --mkdir est idempotent côté virt-customize.
virt-customize -a "$DISK" \
  --mkdir /etc/systemd/network \
  --upload /tmp/cfg/networkd.network:/etc/systemd/network/99-shiftwise.network \
  --mkdir /etc/network/interfaces.d \
  --upload /tmp/cfg/ifupdown.cfg:/etc/network/interfaces.d/99-shiftwise.cfg \
  --mkdir /etc/NetworkManager/system-connections \
  --upload /tmp/cfg/nm.nmconnection:/etc/NetworkManager/system-connections/99-shiftwise.nmconnection \
  --mkdir /etc/netplan \
  --upload /tmp/cfg/netplan.yaml:/etc/netplan/99-shiftwise.yaml \
  --run-command 'chmod 600 /etc/NetworkManager/system-connections/99-shiftwise.nmconnection 2>/dev/null || true' \
  --run-command 'chmod 600 /etc/netplan/99-shiftwise.yaml 2>/dev/null || true' \
  --run-command 'systemctl enable serial-getty@ttyS0.service 2>/dev/null || true' \
  --run-command 'systemctl enable systemd-networkd.service 2>/dev/null || true' \
  --run-command 'systemctl enable NetworkManager.service 2>/dev/null || true' \
  --run-command 'sed -i -E "s|^GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT=\"console=tty0 console=ttyS0,115200n8\"|" /etc/default/grub 2>/dev/null || true' \
  --run-command 'update-grub 2>/dev/null || grub2-mkconfig -o /boot/grub2/grub.cfg 2>/dev/null || true' \
  --selinux-relabel \
  || {
    echo "ERROR virt-customize exit $?"
    exit 1
  }

echo ">>> Adapter done"
"""


@dataclass(frozen=True)
class AdapterOutcome:
    succeeded: bool
    failure_reason: Optional[str]
    container_exit_code: Optional[int]


def adapter_job_name(migration_id: int, disk_index: int) -> str:
    return f"shiftwise-adapt-{int(migration_id)}-d{int(disk_index)}"


def submit_adapter_job(
    *,
    namespace: str,
    job_name: str,
    migration_id: int,
    disk_index: int,
    src_relative_path: str,
    backoff_limit: int = 0,
    active_deadline_seconds: int = 30 * 60,
) -> str:
    """Submit the adapter Job. Idempotent on AlreadyExists."""
    kv = get_kubevirt_client()
    manifest = _build_manifest(
        namespace=namespace,
        job_name=job_name,
        migration_id=migration_id,
        disk_index=disk_index,
        src_relative_path=src_relative_path,
        backoff_limit=backoff_limit,
        active_deadline_seconds=active_deadline_seconds,
    )
    try:
        kv.batch_api.create_namespaced_job(namespace=namespace, body=manifest)
        logger.info("Submitted adapter Job %s/%s", namespace, job_name)
    except ApiException as e:
        if e.status == 409:
            logger.info("Adapter Job %s/%s already exists — reusing",
                        namespace, job_name)
            return job_name
        if e.status in (401, 403):
            raise AdapterError(
                "ERR_ADAPT_NAMESPACE_FORBIDDEN",
                f"Worker SA cannot create Jobs in {namespace!r}: {e}",
                cause=e,
            ) from e
        raise AdapterError(
            "ERR_ADAPT_K8S_TIMEOUT",
            f"K8s refused adapter Job {namespace}/{job_name}: {e}",
            cause=e,
        ) from e
    return job_name


def wait_for_adapter(
    *,
    namespace: str,
    job_name: str,
    poll_interval_seconds: float = 5.0,
    timeout_seconds: Optional[int] = None,
) -> AdapterOutcome:
    """Block until the Job reaches a terminal state."""
    kv = get_kubevirt_client()
    start = time.monotonic()
    while True:
        try:
            job = kv.batch_api.read_namespaced_job_status(
                name=job_name, namespace=namespace,
            )
        except ApiException as e:
            raise AdapterError(
                "ERR_ADAPT_K8S_TIMEOUT",
                f"Could not read adapter Job {namespace}/{job_name}: {e}",
                cause=e,
            ) from e

        status = job.status
        if status.succeeded and status.succeeded >= 1:
            return AdapterOutcome(succeeded=True, failure_reason=None,
                                  container_exit_code=0)
        if status.failed and status.failed >= 1:
            return AdapterOutcome(
                succeeded=False,
                failure_reason=_extract_failure_reason(job),
                container_exit_code=_extract_exit_code(namespace, job_name),
            )

        if timeout_seconds is not None and (time.monotonic() - start) > timeout_seconds:
            return AdapterOutcome(
                succeeded=False, failure_reason="TimeoutInClient",
                container_exit_code=None,
            )

        time.sleep(poll_interval_seconds)


def get_adapter_logs(*, namespace: str, job_name: str) -> str:
    """Concatenate logs from all pods of the adapter Job."""
    kv = get_kubevirt_client()
    try:
        pods = kv.core_api.list_namespaced_pod(
            namespace=namespace, label_selector=f"job-name={job_name}",
        )
    except ApiException as e:
        logger.warning("Could not list pods for adapter %s/%s: %s",
                       namespace, job_name, e)
        return ""

    chunks: list[str] = []
    for pod in pods.items:
        try:
            log = kv.core_api.read_namespaced_pod_log(
                name=pod.metadata.name, namespace=namespace, tail_lines=4000,
            )
            chunks.append(log or "")
        except ApiException as e:
            chunks.append(f"[error reading log for pod {pod.metadata.name}: {e}]")
    return "\n---\n".join(chunks)


def delete_adapter(*, namespace: str, job_name: str) -> None:
    from kubernetes import client as k8s_client
    kv = get_kubevirt_client()
    body = k8s_client.V1DeleteOptions(propagation_policy="Foreground")
    try:
        kv.batch_api.delete_namespaced_job(
            name=job_name, namespace=namespace, body=body,
        )
    except ApiException as e:
        if e.status != 404:
            logger.warning("Could not delete adapter %s/%s: %s",
                           namespace, job_name, e)


# --- internals -------------------------------------------------------------

def _build_manifest(
    *,
    namespace: str,
    job_name: str,
    migration_id: int,
    disk_index: int,
    src_relative_path: str,
    backoff_limit: int,
    active_deadline_seconds: int,
) -> dict:
    labels = {
        _LABEL_APP: _LABEL_APP_VAL,
        _LABEL_MIGRATION: str(migration_id),
        _LABEL_DISK: str(disk_index),
    }
    disk_path = f"/src/{src_relative_path.lstrip('/')}"

    return {
        "apiVersion": "batch/v1",
        "kind": "Job",
        "metadata": {
            "name": job_name,
            "namespace": namespace,
            "labels": labels,
        },
        "spec": {
            "backoffLimit": backoff_limit,
            "activeDeadlineSeconds": active_deadline_seconds,
            "ttlSecondsAfterFinished": 24 * 3600,
            "template": {
                "metadata": {"labels": labels},
                "spec": {
                    "restartPolicy": "Never",
                    "serviceAccountName": settings.MIGRATOR_POPULATOR_SA,
                    "containers": [{
                        "name": "adapter",
                        "image": settings.ADAPTER_IMAGE,
                        "imagePullPolicy": "IfNotPresent",
                        "command": ["/bin/bash", "-c", _FIXUP_SCRIPT],
                        "env": [
                            {"name": "DISK_PATH", "value": disk_path},
                            # libguestfs auto-detects /dev/kvm; falls back to
                            # TCG when missing. Disable user-mode caching so
                            # NFS-backed mutations are visible immediately.
                            {"name": "LIBGUESTFS_BACKEND", "value": "direct"},
                            {"name": "LIBGUESTFS_CACHEDIR", "value": "/tmp"},
                        ],
                        "securityContext": {
                            # /dev/kvm requires privileged on OpenShift 4.18.
                            # Default False -> libguestfs falls back to TCG
                            # (functional, ~5x slower). Set ADAPTER_PRIVILEGED=
                            # True if you have the KubeVirt device plugin and
                            # an SCC granting privileged to the adapter SA.
                            "privileged": settings.ADAPTER_PRIVILEGED,
                        },
                        "volumeMounts": [
                            {"name": "src", "mountPath": "/src"},
                        ],
                        "resources": {
                            "requests": {"cpu": "200m", "memory": "512Mi"},
                            "limits":   {"cpu": "2",    "memory": "2Gi"},
                        },
                    }],
                    "volumes": [
                        # Source NFS, RW: virt-customize mutates the qcow2.
                        {
                            "name": "src",
                            "nfs": {
                                "server": settings.MIGRATOR_NFS_SERVER,
                                "path": settings.MIGRATOR_NFS_PATH,
                            },
                        },
                    ],
                },
            },
        },
    }


def _extract_failure_reason(job) -> Optional[str]:
    for cond in (job.status.conditions or []):
        if cond.type == "Failed" and cond.status == "True":
            return cond.reason or cond.message
    return None


def _extract_exit_code(namespace: str, job_name: str) -> Optional[int]:
    kv = get_kubevirt_client()
    try:
        pods = kv.core_api.list_namespaced_pod(
            namespace=namespace, label_selector=f"job-name={job_name}",
        )
    except ApiException:
        return None
    for pod in pods.items:
        for cs in (pod.status.container_statuses or []):
            term = cs.state.terminated if cs.state else None
            if term is not None and term.exit_code is not None:
                return int(term.exit_code)
    return None
