"""
Guest fixup K8s Job — runs virt-customize on a qcow2 in place.

Strategy:
    Mount the transit NFS export RW on the pod (same SCC as populator,
    nfs volume allowed via shiftwise-populator SCC). Run a self-contained
    bash script that:
        1. Drops a generic DHCP config matching all common virtio NIC names
           (covers ifupdown, systemd-networkd, NetworkManager — whichever
           the guest uses, only one will pick it up).
        2. Enables ``serial-getty@ttyS0`` so KubeVirt's ``virtctl console``
           works.
        3. Patches GRUB to send kernel boot logs to ttyS0 too.
        4. For a UEFI guest, installs the distro's GRUB at the EFI
           removable-media fallback path (``\\EFI\\BOOT\\BOOTX64.EFI``). A
           KubeVirt VM boots with fresh/empty EFI NVRAM, so the source's boot
           entry is gone; a stock Ubuntu/RHEL ESP falls back to shim, which
           then loops in ``fbx64.efi`` trying to recreate the NVRAM entry.
           Pointing the fallback straight at GRUB boots the guest deterministically
           (no shim/NVRAM dance; safe because SecureBoot is off). No-op on a
           BIOS guest (no ESP).
        5. SELinux relabel.

Idempotent — running twice on the same disk is safe (writes overwrite,
systemctl enable is no-op if already enabled).

KVM acceleration:
    libguestfs uses ``/dev/kvm`` if available (privileged + KVM device
    plugin on the node). Otherwise it falls back to TCG which is 5–10×
    slower. We try privileged first; if the cluster admin has not enabled
    KVM, we still finish (just slowly). The Job is privileged because
    /dev/kvm requires it on OpenShift 4.18 by default.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass
from typing import Optional

from kubernetes.client.rest import ApiException

from app.core.config import settings
from app.core.kubevirt_client import get_kubevirt_client
from app.models.hypervisor import HypervisorType
from app.models.virtual_machine import OSType
from app.services.adapter.errors import AdapterError
from app.services.migrator.transit_discovery import discover_transit_nfs

logger = logging.getLogger(__name__)


_LABEL_APP = "app.shiftwise.io/component"
_LABEL_APP_VAL = "adapter"
_LABEL_MIGRATION = "app.shiftwise.io/migration-id"
_LABEL_DISK = "app.shiftwise.io/disk-index"

# Audit E9 — client-side HTTP timeout for the poll-loop Job read, so a hung
# API server cannot wedge the worker thread forever inside one read call.
_K8S_READ_TIMEOUT_SECONDS = 30


# The fixup script. Embedded here rather than as a ConfigMap because:
#   1. It's small (< 4 KiB).
#   2. Versioning happens in the Python source — every code change
#      bumps the script atomically with the orchestrator that uses it.
#   3. No extra ConfigMap to manage in tenant namespaces.
#
# All operations are idempotent and use ``|| true`` to survive missing
# files (GRUB on Ubuntu vs grub2 on RHEL, etc.).
_LINUX_FIXUP_SCRIPT = r"""#!/bin/bash
set -eu
DISK="${DISK_PATH:?missing DISK_PATH}"

echo ">>> Adapter starting on $DISK (Linux guest — virt-customize)"
ls -la "$DISK"

# OpenShift assigne une UID différente par namespace. Le qcow2 a été écrit
# par le converter dans le namespace `shiftwise` (UID 1000760000) alors que
# l'adapter tourne dans le namespace tenant `shiftwise-{tenant}` (UID
# 1000790000). Sans les permissions group-write, qemu refuse d'ouvrir le
# fichier en RW. Chmod 0666 explicite — la donnée est sur un partage NFS
# interne au cluster, accessible uniquement aux SAs autorisés.
chmod 0666 "$DISK" || {
  echo "WARN: chmod failed (file probably read-only on NFS); continuing"
}
ls -la "$DISK"

mkdir -p /tmp/cfg

# systemd-networkd: matches every virtio interface name pattern at once.
cat > /tmp/cfg/networkd.network <<'EOF'
[Match]
Name=en* eth*
[Network]
DHCP=yes
EOF

# ifupdown (Debian default with /etc/network/interfaces).
# We list every realistic virtio name; missing interfaces are silently
# skipped by ifup.
cat > /tmp/cfg/ifupdown.cfg <<'EOF'
# Auto-generated by ShiftWise Adapter — DHCP on any common virtio NIC name.
auto enp1s0
iface enp1s0 inet dhcp

auto enp2s0
iface enp2s0 inet dhcp

auto ens2
iface ens2 inet dhcp

auto ens3
iface ens3 inet dhcp

auto eth0
iface eth0 inet dhcp
EOF

# NetworkManager keyfile (RHEL/Fedora/Ubuntu default).
cat > /tmp/cfg/nm.nmconnection <<'EOF'
[connection]
id=shiftwise-dhcp
type=ethernet
autoconnect=true
[ipv4]
method=auto
[ipv6]
method=auto
EOF

# netplan (Ubuntu 18+).
cat > /tmp/cfg/netplan.yaml <<'EOF'
network:
  version: 2
  ethernets:
    all-en:
      match: {name: "en*"}
      dhcp4: true
      dhcp6: true
    all-eth:
      match: {name: "eth*"}
      dhcp4: true
EOF

# libguestfs backend: even a privileged adapter pod on these nodes cannot use
# KVM acceleration (no usable nested virt exposed to the pod), so the default
# backend makes guestfs_launch fail ("appliance failed to start"). Force the
# direct/TCG backend (software emulation) — slower, but it reliably boots the
# appliance. On a node with working /dev/kvm this can be relaxed for ~5x speed.
export LIBGUESTFS_BACKEND=direct
export LIBGUESTFS_BACKEND_SETTINGS=force_tcg
echo ">>> libguestfs backend=direct force_tcg (software emulation)"

echo ">>> Running virt-customize"
# --mkdir avant chaque --upload : les dossiers /etc/NetworkManager,
# /etc/systemd/network, /etc/netplan n'existent que si la stack
# correspondante est installée. virt-customize --upload ne crée pas le
# parent automatiquement. --mkdir est idempotent côté virt-customize.
virt-customize -a "$DISK" \
  --mkdir /etc/systemd/network \
  --upload /tmp/cfg/networkd.network:/etc/systemd/network/99-shiftwise.network \
  --mkdir /etc/network/interfaces.d \
  --upload /tmp/cfg/ifupdown.cfg:/etc/network/interfaces.d/99-shiftwise.cfg \
  --mkdir /etc/NetworkManager/system-connections \
  --upload /tmp/cfg/nm.nmconnection:/etc/NetworkManager/system-connections/99-shiftwise.nmconnection \
  --mkdir /etc/netplan \
  --upload /tmp/cfg/netplan.yaml:/etc/netplan/99-shiftwise.yaml \
  --run-command 'chmod 600 /etc/NetworkManager/system-connections/99-shiftwise.nmconnection 2>/dev/null || true' \
  --run-command 'chmod 600 /etc/netplan/99-shiftwise.yaml 2>/dev/null || true' \
  --run-command 'systemctl enable serial-getty@ttyS0.service 2>/dev/null || true' \
  --run-command 'systemctl enable systemd-networkd.service 2>/dev/null || true' \
  --run-command 'systemctl enable NetworkManager.service 2>/dev/null || true' \
  --run-command 'sed -i -E "s|^GRUB_CMDLINE_LINUX_DEFAULT=.*|GRUB_CMDLINE_LINUX_DEFAULT=\"console=tty0 console=ttyS0,115200n8\"|" /etc/default/grub 2>/dev/null || true' \
  --run-command 'update-grub 2>/dev/null || grub2-mkconfig -o /boot/grub2/grub.cfg 2>/dev/null || true' \
  --run-command 'for v in ubuntu debian centos redhat fedora rocky almalinux sles opensuse; do if [ -d /boot/efi/EFI/BOOT ] && [ -f /boot/efi/EFI/$v/grubx64.efi ]; then cp -f /boot/efi/EFI/$v/grubx64.efi /boot/efi/EFI/BOOT/grubx64.efi; cp -f /boot/efi/EFI/$v/grubx64.efi /boot/efi/EFI/BOOT/BOOTX64.EFI; fi; done 2>/dev/null || true' \
  --selinux-relabel \
  || {
    echo "ERROR virt-customize exit $?"
    exit 1
  }

echo ">>> Adapter done"
"""


# Virtio initramfs regeneration — a guest captured from a non-virtio source
# (bare-metal P2V, VMware ESXi/vSphere/Workstation, Hyper-V) has an initramfs
# built for that platform's storage/network drivers (vmw_pvscsi, mptspi,
# hv_storvsc, …) and NO virtio modules. Under KubeVirt the root disk sits on
# the virtio bus, so such a guest cannot find its root device and stalls/panics
# on first boot. Regenerate the initramfs with virtio forced in. Exactly one
# regenerator runs, selected by the guest's init tooling: initramfs-tools
# (`update-initramfs`, Debian/Ubuntu) is preferred, else dracut (RHEL/Fedora).
# They are mutually exclusive on purpose — running BOTH double-regenerates and,
# under the TCG appliance, `dracut --regenerate-all` (every installed kernel) on
# a guest that also ships update-initramfs OOM-kills the appliance. Idempotent —
# harmless on a guest that already ships virtio (KVM/Proxmox/oVirt sources), so
# it is gated off there only to avoid a redundant (slow, TCG) second
# virt-customize launch, not for safety.
_VIRTIO_INITRAMFS_FIXUP = r"""
echo ">>> virtio: forcing virtio drivers into the initramfs"
virt-customize -a "$DISK" \
  --run-command 'echo "virtio_blk virtio_net virtio_pci virtio_scsi" | tr " " "\n" >> /etc/initramfs-tools/modules 2>/dev/null || true' \
  --run-command 'mkdir -p /etc/dracut.conf.d && echo '\''add_drivers+=" virtio_blk virtio_net virtio_pci virtio_scsi "'\'' > /etc/dracut.conf.d/99-shiftwise-virtio.conf 2>/dev/null || true' \
  --run-command 'if command -v update-initramfs >/dev/null 2>&1; then update-initramfs -u; elif command -v dracut >/dev/null 2>&1; then dracut --regenerate-all --force; fi 2>/dev/null || true' \
  || {
    echo "ERROR virtio initramfs virt-customize exit $?"
    exit 1
  }
echo ">>> virtio: initramfs regeneration done"
"""


# Windows guest path — virt-customize cannot configure DHCP / serial on a
# Windows partition (NTFS plus driver-injection requirements). The standard
# tool is libguestfs's `virt-v2v-in-place`, which:
#   - injects Red Hat-signed virtio drivers (NIC, balloon, viostor) so the
#     guest boots on KubeVirt's virtio bus
#   - drops VMware Tools / Hyper-V Integration Services
#   - sets the new NIC to DHCP and runs a first-boot Windows script that
#     activates the drivers after the next boot
#
# Requires the image to ship the virtio-win driver ISO at
# /usr/share/virtio-win (the default location libguestfs looks at — picked
# up via the VIRTIO_WIN env var). On a Debian-based ADAPTER_IMAGE this
# means installing the `virtio-win` package or unpacking the upstream ISO
# into that path during image build.
_WINDOWS_FIXUP_SCRIPT = r"""#!/bin/bash
set -eu
DISK="${DISK_PATH:?missing DISK_PATH}"

echo ">>> Adapter starting on $DISK (Windows guest — virt-v2v-in-place)"
ls -la "$DISK"

# Cross-namespace UID workaround — same as the Linux path. The qcow2 was
# written by the converter under the `shiftwise` namespace UID; the adapter
# Job runs under the tenant-namespace UID. NTFS host-side permissions are
# governed by the file mode on the qcow2 container, not the in-guest ACL.
chmod 0666 "$DISK" || {
  echo "WARN: chmod failed (file probably read-only on NFS); continuing"
}
ls -la "$DISK"

# virt-v2v-in-place picks up virtio drivers from $VIRTIO_WIN. The default
# /usr/share/virtio-win is honoured if unset, but spelling it out here makes
# the failure mode (missing ISO) obvious in the log.
export VIRTIO_WIN="${VIRTIO_WIN:-/usr/share/virtio-win}"
if [ ! -d "$VIRTIO_WIN" ] && [ ! -f "$VIRTIO_WIN" ]; then
  echo "ERROR: virtio-win drivers not found at $VIRTIO_WIN"
  echo "       The ADAPTER_IMAGE must ship the virtio-win ISO or expanded tree"
  echo "       at that path — Windows guest adaptation cannot proceed without it."
  exit 1
fi

echo ">>> Running virt-v2v-in-place"
# -i disk: input is a raw disk image (we converted to qcow2 upstream, which
#          libguestfs detects via its header — no need to declare format).
# -v -x : verbose + trace, lands in the Job pod log for diagnosis.
virt-v2v-in-place -v -x -i disk "$DISK" || {
  echo "ERROR virt-v2v-in-place exit $?"
  exit 1
}

echo ">>> Adapter done"
"""


# Sources whose guests already run on the virtio bus — their initramfs ships
# virtio_blk/virtio_scsi/virtio_net, so the extra (slow, TCG) initramfs
# regeneration is redundant and skipped. Every OTHER source (VMware ESXi /
# vSphere / Workstation, Hyper-V, physical P2V, Xen, VirtualBox, unknown) needs
# virtio forced into the initramfs or the migrated guest cannot find its root
# device on KubeVirt's virtio bus and stalls at boot.
_VIRTIO_NATIVE_SOURCES = frozenset({
    HypervisorType.KVM,
    HypervisorType.PROXMOX,
    HypervisorType.OVIRT,
})


def _needs_virtio_injection(hv_type: Optional[HypervisorType]) -> bool:
    """True when the source guest's initramfs must have virtio forced in.

    Defaults to True for an unknown / missing source type — injecting virtio is
    safe (idempotent) on a guest that already has it, whereas omitting it on a
    guest that does not bricks the boot. Better a redundant step than a VM that
    hangs at ``Booting from Hard Disk...``.
    """
    return hv_type not in _VIRTIO_NATIVE_SOURCES


def _fixup_script_for_os(os_type: OSType, *, inject_virtio: bool = False) -> str:
    """Pick the libguestfs strategy that fits the guest OS family.

    Windows guests need `virt-v2v-in-place` (virtio driver injection plus
    Windows first-boot scripting). Linux — and OTHER/UNKNOWN as a safe
    fallback — use the multi-stack DHCP / serial-console / GRUB script driven
    by `virt-customize`.

    ``inject_virtio`` appends a virtio-initramfs regeneration step to the Linux
    fixup — a guest captured from a non-virtio source (VMware, Hyper-V, physical)
    has no virtio drivers in its initramfs and would stall looking for its root
    device under KubeVirt. Ignored for Windows (virt-v2v-in-place already
    injects virtio drivers).
    """
    if os_type == OSType.WINDOWS:
        return _WINDOWS_FIXUP_SCRIPT
    if inject_virtio:
        return _LINUX_FIXUP_SCRIPT + _VIRTIO_INITRAMFS_FIXUP
    return _LINUX_FIXUP_SCRIPT


@dataclass(frozen=True)
class AdapterOutcome:
    succeeded: bool
    failure_reason: Optional[str]
    container_exit_code: Optional[int]


def adapter_job_name(migration_id: int, disk_index: int) -> str:
    return f"shiftwise-adapt-{int(migration_id)}-d{int(disk_index)}"


def _existing_job_is_reusable(kv, namespace: str, job_name: str) -> bool:
    """True if the named Job can be reused as-is (active or already succeeded).

    Only a Job that has ``failed`` (and not succeeded) is a stale leftover from a
    failed run that must be deleted + recreated for the retry — re-running an
    already-succeeded adaptation would waste ~15 min under the TCG appliance, and
    reusing it lets the orchestrator move straight to the next stage. A read
    failure is treated as non-reusable so the caller deletes + recreates (safe:
    delete is idempotent).
    """
    try:
        job = kv.batch_api.read_namespaced_job_status(
            name=job_name, namespace=namespace,
            _request_timeout=_K8S_READ_TIMEOUT_SECONDS,
        )
    except ApiException:
        return False
    status = job.status
    if (status.failed or 0) >= 1 and (status.succeeded or 0) < 1:
        return False  # stale failed Job — retry needs a fresh one
    return True  # active, or already succeeded — reuse


def _delete_job_and_wait(
    kv, namespace: str, job_name: str,
    *, timeout_seconds: float = 60.0, poll_seconds: float = 1.0,
) -> None:
    """Delete a Job (and its pods, Foreground propagation) and wait until gone.

    Foreground propagation ensures the pods are reaped before we recreate a Job
    of the same name, avoiding an orphaned pod racing the new one.
    """
    from kubernetes import client as k8s_client

    try:
        kv.batch_api.delete_namespaced_job(
            name=job_name, namespace=namespace,
            body=k8s_client.V1DeleteOptions(propagation_policy="Foreground"),
            _request_timeout=_K8S_READ_TIMEOUT_SECONDS,
        )
    except ApiException as e:
        if e.status == 404:
            return
        raise AdapterError(
            "ERR_ADAPT_K8S_TIMEOUT",
            f"Could not delete stale adapter Job {namespace}/{job_name}: {e}",
            cause=e,
        ) from e
    deadline = time.monotonic() + timeout_seconds
    while time.monotonic() < deadline:
        try:
            kv.batch_api.read_namespaced_job_status(
                name=job_name, namespace=namespace,
                _request_timeout=_K8S_READ_TIMEOUT_SECONDS,
            )
        except ApiException as e:
            if e.status == 404:
                return  # fully deleted
        time.sleep(poll_seconds)
    raise AdapterError(
        "ERR_ADAPT_K8S_TIMEOUT",
        f"Stale adapter Job {namespace}/{job_name} not deleted within "
        f"{timeout_seconds}s",
    )


def submit_adapter_job(
    *,
    namespace: str,
    job_name: str,
    migration_id: int,
    disk_index: int,
    src_relative_path: str,
    os_type: OSType = OSType.LINUX,
    inject_virtio: bool = False,
    backoff_limit: int = 0,
    active_deadline_seconds: int = 30 * 60,
) -> str:
    """Submit the adapter Job. Idempotent on AlreadyExists.

    ``os_type`` selects the in-pod fixup strategy: WINDOWS uses
    `virt-v2v-in-place`, everything else falls through to the Linux
    multi-stack DHCP / serial-console script.
    """
    kv = get_kubevirt_client()
    # Audit C-07 : découvrir le serveur/chemin NFS de transit depuis le PV
    # lié, comme le fait le populator. settings.MIGRATOR_NFS_* est vide par
    # défaut — coder en dur ces valeurs faisait échouer le montage NFS du
    # pod adapter sur tout déploiement sans surcharge manuelle.
    nfs_server, nfs_path = discover_transit_nfs(kv)
    manifest = _build_manifest(
        namespace=namespace,
        job_name=job_name,
        migration_id=migration_id,
        disk_index=disk_index,
        src_relative_path=src_relative_path,
        nfs_server=nfs_server,
        nfs_path=nfs_path,
        os_type=os_type,
        inject_virtio=inject_virtio,
        backoff_limit=backoff_limit,
        active_deadline_seconds=active_deadline_seconds,
    )
    try:
        kv.batch_api.create_namespaced_job(namespace=namespace, body=manifest)
        logger.info("Submitted adapter Job %s/%s", namespace, job_name)
    except ApiException as e:
        if e.status == 409:
            # A Job with this (deterministic) name already exists. If it is still
            # active it is a re-delivered in-flight task — reuse it. If it already
            # reached a terminal state it is a stale Job from a previous *failed*
            # run; reusing it would instantly resurface that old failure (e.g. a
            # DeadlineExceeded), so delete it and recreate fresh for the retry.
            if _existing_job_is_reusable(kv, namespace, job_name):
                logger.info("Adapter Job %s/%s reusable — reusing", namespace, job_name)
                return job_name
            logger.info(
                "Adapter Job %s/%s exists in a failed state — deleting and "
                "recreating for retry", namespace, job_name,
            )
            _delete_job_and_wait(kv, namespace, job_name)
            kv.batch_api.create_namespaced_job(namespace=namespace, body=manifest)
            logger.info("Resubmitted adapter Job %s/%s", namespace, job_name)
            return job_name
        if e.status in (401, 403):
            raise AdapterError(
                "ERR_ADAPT_NAMESPACE_FORBIDDEN",
                f"Worker SA cannot create Jobs in {namespace!r}: {e}",
                cause=e,
            ) from e
        raise AdapterError(
            "ERR_ADAPT_K8S_TIMEOUT",
            f"K8s refused adapter Job {namespace}/{job_name}: {e}",
            cause=e,
        ) from e
    return job_name


def wait_for_adapter(
    *,
    namespace: str,
    job_name: str,
    poll_interval_seconds: float = 5.0,
    timeout_seconds: Optional[int] = None,
) -> AdapterOutcome:
    """Block until the Job reaches a terminal state."""
    kv = get_kubevirt_client()
    start = time.monotonic()
    while True:
        try:
            job = kv.batch_api.read_namespaced_job_status(
                name=job_name, namespace=namespace,
                _request_timeout=_K8S_READ_TIMEOUT_SECONDS,  # Audit E9
            )
        except ApiException as e:
            raise AdapterError(
                "ERR_ADAPT_K8S_TIMEOUT",
                f"Could not read adapter Job {namespace}/{job_name}: {e}",
                cause=e,
            ) from e

        status = job.status
        if status.succeeded and status.succeeded >= 1:
            return AdapterOutcome(succeeded=True, failure_reason=None,
                                  container_exit_code=0)
        if status.failed and status.failed >= 1:
            return AdapterOutcome(
                succeeded=False,
                failure_reason=_extract_failure_reason(job),
                container_exit_code=_extract_exit_code(namespace, job_name),
            )

        if timeout_seconds is not None and (time.monotonic() - start) > timeout_seconds:
            return AdapterOutcome(
                succeeded=False, failure_reason="TimeoutInClient",
                container_exit_code=None,
            )

        time.sleep(poll_interval_seconds)


def get_adapter_logs(*, namespace: str, job_name: str) -> str:
    """Concatenate logs from all pods of the adapter Job."""
    kv = get_kubevirt_client()
    try:
        pods = kv.core_api.list_namespaced_pod(
            namespace=namespace, label_selector=f"job-name={job_name}",
        )
    except ApiException as e:
        logger.warning("Could not list pods for adapter %s/%s: %s",
                       namespace, job_name, e)
        return ""

    chunks: list[str] = []
    for pod in pods.items:
        try:
            log = kv.core_api.read_namespaced_pod_log(
                name=pod.metadata.name, namespace=namespace, tail_lines=4000,
            )
            chunks.append(log or "")
        except ApiException as e:
            chunks.append(f"[error reading log for pod {pod.metadata.name}: {e}]")
    return "\n---\n".join(chunks)


def delete_adapter(*, namespace: str, job_name: str) -> None:
    from kubernetes import client as k8s_client
    kv = get_kubevirt_client()
    body = k8s_client.V1DeleteOptions(propagation_policy="Foreground")
    try:
        kv.batch_api.delete_namespaced_job(
            name=job_name, namespace=namespace, body=body,
        )
    except ApiException as e:
        if e.status != 404:
            logger.warning("Could not delete adapter %s/%s: %s",
                           namespace, job_name, e)


# --- internals -------------------------------------------------------------

def _build_manifest(
    *,
    namespace: str,
    job_name: str,
    migration_id: int,
    disk_index: int,
    src_relative_path: str,
    nfs_server: str,
    nfs_path: str,
    backoff_limit: int,
    active_deadline_seconds: int,
    os_type: OSType = OSType.LINUX,
    inject_virtio: bool = False,
) -> dict:
    labels = {
        _LABEL_APP: _LABEL_APP_VAL,
        _LABEL_MIGRATION: str(migration_id),
        _LABEL_DISK: str(disk_index),
    }
    disk_path = f"/src/{src_relative_path.lstrip('/')}"
    fixup_script = _fixup_script_for_os(os_type, inject_virtio=inject_virtio)

    return {
        "apiVersion": "batch/v1",
        "kind": "Job",
        "metadata": {
            "name": job_name,
            "namespace": namespace,
            "labels": labels,
        },
        "spec": {
            "backoffLimit": backoff_limit,
            "activeDeadlineSeconds": active_deadline_seconds,
            "ttlSecondsAfterFinished": 24 * 3600,
            "template": {
                "metadata": {"labels": labels},
                "spec": {
                    "restartPolicy": "Never",
                    "serviceAccountName": settings.MIGRATOR_POPULATOR_SA,
                    "containers": [{
                        "name": "adapter",
                        "image": settings.ADAPTER_IMAGE,
                        "imagePullPolicy": "IfNotPresent",
                        "command": ["/bin/bash", "-c", fixup_script],
                        "env": [
                            {"name": "DISK_PATH", "value": disk_path},
                            # libguestfs auto-detects /dev/kvm; falls back to
                            # TCG when missing. Disable user-mode caching so
                            # NFS-backed mutations are visible immediately.
                            {"name": "LIBGUESTFS_BACKEND", "value": "direct"},
                            {"name": "LIBGUESTFS_CACHEDIR", "value": "/tmp"},
                        ],
                        "securityContext": {
                            # /dev/kvm requires privileged on OpenShift 4.18.
                            # Default False -> libguestfs falls back to TCG
                            # (functional, ~5x slower). Set ADAPTER_PRIVILEGED=
                            # True if you have the KubeVirt device plugin and
                            # an SCC granting privileged to the adapter SA.
                            "privileged": settings.ADAPTER_PRIVILEGED,
                        },
                        "volumeMounts": [
                            {"name": "src", "mountPath": "/src"},
                        ],
                        "resources": {
                            "requests": {"cpu": "200m", "memory": "512Mi"},
                            "limits":   {"cpu": "2",    "memory": "2Gi"},
                        },
                    }],
                    "volumes": [
                        # Source NFS, RW: virt-customize mutates the qcow2.
                        {
                            "name": "src",
                            "nfs": {
                                "server": nfs_server,
                                "path": nfs_path,
                            },
                        },
                    ],
                },
            },
        },
    }


def _extract_failure_reason(job) -> Optional[str]:
    # Audit E18 — return the condition's `reason` field ONLY. The free-text
    # `message` field would poison any exact-match classification keyed on
    # the short reason code (e.g. "BackoffLimitExceeded", "DeadlineExceeded").
    for cond in (job.status.conditions or []):
        if cond.type == "Failed" and cond.status == "True":
            return cond.reason
    return None


def _extract_exit_code(namespace: str, job_name: str) -> Optional[int]:
    kv = get_kubevirt_client()
    try:
        pods = kv.core_api.list_namespaced_pod(
            namespace=namespace, label_selector=f"job-name={job_name}",
        )
    except ApiException:
        return None
    for pod in pods.items:
        for cs in (pod.status.container_statuses or []):
            term = cs.state.terminated if cs.state else None
            if term is not None and term.exit_code is not None:
                return int(term.exit_code)
    return None
