"""remove created_by column from base model

Revision ID: 1448c28c60e7
Revises: 6df4321f49f3
Create Date: 2026-03-10 18:18:55.091085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1448c28c60e7'
down_revision: Union[str, None] = '6df4321f49f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
