"""remove created_by column from base model

Revision ID: 610294f89e89
Revises: 8881eab06db1
Create Date: 2026-03-10 17:25:33.531805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '610294f89e89'
down_revision: Union[str, None] = '8881eab06db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hypervisors_created_by_fkey', 'hypervisors', type_='foreignkey')
    op.drop_column('hypervisors', 'created_by')
    op.drop_constraint('migrations_created_by_fkey', 'migrations', type_='foreignkey')
    op.drop_column('migrations', 'created_by')
    op.drop_constraint('roles_created_by_fkey', 'roles', type_='foreignkey')
    op.drop_column('roles', 'created_by')
    op.drop_constraint('users_created_by_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'created_by')
    op.drop_constraint('virtual_machines_created_by_fkey', 'virtual_machines', type_='foreignkey')
    op.drop_column('virtual_machines', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_machines', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True, comment="ID de l'utilisateur ayant créé cet enregistrement"))
    op.create_foreign_key('virtual_machines_created_by_fkey', 'virtual_machines', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True, comment="ID de l'utilisateur ayant créé cet enregistrement"))
    op.create_foreign_key('users_created_by_fkey', 'users', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('roles', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True, comment="ID de l'utilisateur ayant créé cet enregistrement"))
    op.create_foreign_key('roles_created_by_fkey', 'roles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('migrations', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True, comment="ID de l'utilisateur ayant créé cet enregistrement"))
    op.create_foreign_key('migrations_created_by_fkey', 'migrations', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('hypervisors', sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True, comment="ID de l'utilisateur ayant créé cet enregistrement"))
    op.create_foreign_key('hypervisors_created_by_fkey', 'hypervisors', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
