"""add created_by column to all tables

Revision ID: 8881eab06db1
Revises: b8951ce66d27
Create Date: 2026-03-10 17:08:05.562140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8881eab06db1'
down_revision: Union[str, None] = 'b8951ce66d27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hypervisors', sa.Column('created_by', sa.Integer(), nullable=True, comment="ID de l'utilisateur ayant créé cet enregistrement"))
    op.create_foreign_key(None, 'hypervisors', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('migrations', sa.Column('created_by', sa.Integer(), nullable=True, comment="ID de l'utilisateur ayant créé cet enregistrement"))
    op.create_foreign_key(None, 'migrations', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('roles', sa.Column('created_by', sa.Integer(), nullable=True, comment="ID de l'utilisateur ayant créé cet enregistrement"))
    op.create_foreign_key(None, 'roles', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True, comment="ID de l'utilisateur ayant créé cet enregistrement"))
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('virtual_machines', sa.Column('created_by', sa.Integer(), nullable=True, comment="ID de l'utilisateur ayant créé cet enregistrement"))
    op.create_foreign_key(None, 'virtual_machines', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'virtual_machines', type_='foreignkey')
    op.drop_column('virtual_machines', 'created_by')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'created_by')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'created_by')
    op.drop_constraint(None, 'migrations', type_='foreignkey')
    op.drop_column('migrations', 'created_by')
    op.drop_constraint(None, 'hypervisors', type_='foreignkey')
    op.drop_column('hypervisors', 'created_by')
    # ### end Alembic commands ###
