"""add timezone to all datetime columns

Revision ID: a9d8d838996f
Revises: 447af6ed6e2d
Create Date: 2026-04-12 01:01:06.713166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9d8d838996f'
down_revision: Union[str, None] = '447af6ed6e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hypervisors', sa.Column('tenant_id', sa.String(length=100), nullable=False))
    op.alter_column('hypervisors', 'last_sync_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('hypervisors', 'last_successful_connection',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_hypervisors_tenant_id'), 'hypervisors', ['tenant_id'], unique=False)
    op.add_column('migrations', sa.Column('tenant_id', sa.String(length=100), nullable=False))
    op.alter_column('migrations', 'scheduled_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('migrations', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('migrations', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('migrations', 'conversion_started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('migrations', 'conversion_completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_migrations_tenant_id'), 'migrations', ['tenant_id'], unique=False)
    op.add_column('virtual_machines', sa.Column('tenant_id', sa.String(length=100), nullable=False))
    op.alter_column('virtual_machines', 'discovered_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('virtual_machines', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_virtual_machines_tenant_id'), 'virtual_machines', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtual_machines_tenant_id'), table_name='virtual_machines')
    op.alter_column('virtual_machines', 'last_seen_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('virtual_machines', 'discovered_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('virtual_machines', 'tenant_id')
    op.drop_index(op.f('ix_migrations_tenant_id'), table_name='migrations')
    op.alter_column('migrations', 'conversion_completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('migrations', 'conversion_started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('migrations', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('migrations', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('migrations', 'scheduled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('migrations', 'tenant_id')
    op.drop_index(op.f('ix_hypervisors_tenant_id'), table_name='hypervisors')
    op.alter_column('hypervisors', 'last_successful_connection',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('hypervisors', 'last_sync_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('hypervisors', 'tenant_id')
    # ### end Alembic commands ###
