"""add virtual_machines, hypervisors, and migrations tables

Revision ID: b8951ce66d27
Revises: 
Create Date: 2026-03-09 10:36:24.452499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8951ce66d27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hypervisors',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('VSPHERE', 'VMWARE_WORKSTATION', 'VMWARE_ESXi', 'HYPER_V', 'KVM', 'PROXMOX', 'VIRTUALBOX', 'XEN', 'OTHER', name='hypervisortype'), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=True),
    sa.Column('ssl_cert_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', 'UNREACHABLE', 'AUTHENTICATING', 'UNKNOWN', name='hypervisorstatus'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_successful_connection', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('total_vms_discovered', sa.Integer(), nullable=True),
    sa.Column('total_vms_migrated', sa.Integer(), nullable=True),
    sa.Column('connection_config', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Date de dernière modification'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypervisors_id'), 'hypervisors', ['id'], unique=False)
    op.create_index(op.f('ix_hypervisors_name'), 'hypervisors', ['name'], unique=True)
    op.create_index(op.f('ix_hypervisors_status'), 'hypervisors', ['status'], unique=False)
    op.create_index(op.f('ix_hypervisors_type'), 'hypervisors', ['type'], unique=False)
    op.create_table('virtual_machines',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_hypervisor_id', sa.Integer(), nullable=True),
    sa.Column('source_uuid', sa.String(length=255), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('memory_mb', sa.Integer(), nullable=False),
    sa.Column('disk_gb', sa.Integer(), nullable=False),
    sa.Column('os_type', sa.Enum('WINDOWS', 'LINUX', 'OTHER', 'UNKNOWN', name='ostype'), nullable=False),
    sa.Column('os_version', sa.String(length=255), nullable=True),
    sa.Column('os_name', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'ANALYZING', 'COMPATIBLE', 'INCOMPATIBLE', 'PARTIAL', 'MIGRATING', 'MIGRATED', 'FAILED', 'ARCHIVED', name='vmstatus'), nullable=False),
    sa.Column('compatibility_status', sa.Enum('COMPATIBLE', 'PARTIAL', 'INCOMPATIBLE', 'UNKNOWN', name='compatibilitystatus'), nullable=False),
    sa.Column('compatibility_details', sa.JSON(), nullable=True),
    sa.Column('openshift_vm_name', sa.String(length=255), nullable=True),
    sa.Column('openshift_namespace', sa.String(length=255), nullable=True),
    sa.Column('openshift_node', sa.String(length=255), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('custom_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['source_hypervisor_id'], ['hypervisors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_machines_compatibility_status'), 'virtual_machines', ['compatibility_status'], unique=False)
    op.create_index(op.f('ix_virtual_machines_id'), 'virtual_machines', ['id'], unique=False)
    op.create_index(op.f('ix_virtual_machines_name'), 'virtual_machines', ['name'], unique=False)
    op.create_index(op.f('ix_virtual_machines_openshift_vm_name'), 'virtual_machines', ['openshift_vm_name'], unique=False)
    op.create_index(op.f('ix_virtual_machines_source_hypervisor_id'), 'virtual_machines', ['source_hypervisor_id'], unique=False)
    op.create_index(op.f('ix_virtual_machines_source_uuid'), 'virtual_machines', ['source_uuid'], unique=False)
    op.create_index(op.f('ix_virtual_machines_status'), 'virtual_machines', ['status'], unique=False)
    op.create_table('migrations',
    sa.Column('vm_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VALIDATING', 'PREPARING', 'TRANSFERRING', 'CONFIGURING', 'STARTING', 'VERIFYING', 'COMPLETED', 'FAILED', 'CANCELLED', 'ROLLBACK', 'ROLLED_BACK', name='migrationstatus'), nullable=False),
    sa.Column('strategy', sa.Enum('DIRECT', 'CONVERSION', 'HYBRID', 'COLD', 'WARM', 'AUTO', name='migrationstrategy'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('current_step', sa.String(length=255), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('current_step_number', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('migration_config', sa.JSON(), nullable=True),
    sa.Column('source_size_gb', sa.Float(), nullable=True),
    sa.Column('transferred_gb', sa.Float(), nullable=True),
    sa.Column('transfer_rate_mbps', sa.Float(), nullable=True),
    sa.Column('target_namespace', sa.String(length=255), nullable=False),
    sa.Column('target_vm_name', sa.String(length=255), nullable=True),
    sa.Column('target_storage_class', sa.String(length=255), nullable=True),
    sa.Column('target_node', sa.String(length=255), nullable=True),
    sa.Column('requires_conversion', sa.Boolean(), nullable=True),
    sa.Column('conversion_format', sa.String(length=50), nullable=True),
    sa.Column('conversion_started_at', sa.DateTime(), nullable=True),
    sa.Column('conversion_completed_at', sa.DateTime(), nullable=True),
    sa.Column('pre_migration_checks', sa.JSON(), nullable=True),
    sa.Column('post_migration_checks', sa.JSON(), nullable=True),
    sa.Column('log_file_path', sa.String(length=512), nullable=True),
    sa.Column('can_rollback', sa.Boolean(), nullable=True),
    sa.Column('rollback_snapshot_id', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment="Date de création de l'enregistrement"),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Date de dernière modification'),
    sa.ForeignKeyConstraint(['vm_id'], ['virtual_machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_migrations_id'), 'migrations', ['id'], unique=False)
    op.create_index(op.f('ix_migrations_status'), 'migrations', ['status'], unique=False)
    op.create_index(op.f('ix_migrations_vm_id'), 'migrations', ['vm_id'], unique=False)
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment="Date de création de l'enregistrement",
               existing_nullable=False)
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Date de dernière modification',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment="Date de création de l'enregistrement",
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Date de dernière modification',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Date de dernière modification',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment="Date de création de l'enregistrement",
               existing_nullable=False)
    op.alter_column('roles', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Date de dernière modification',
               existing_nullable=False)
    op.alter_column('roles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment="Date de création de l'enregistrement",
               existing_nullable=False)
    op.drop_index(op.f('ix_migrations_vm_id'), table_name='migrations')
    op.drop_index(op.f('ix_migrations_status'), table_name='migrations')
    op.drop_index(op.f('ix_migrations_id'), table_name='migrations')
    op.drop_table('migrations')
    op.drop_index(op.f('ix_virtual_machines_status'), table_name='virtual_machines')
    op.drop_index(op.f('ix_virtual_machines_source_uuid'), table_name='virtual_machines')
    op.drop_index(op.f('ix_virtual_machines_source_hypervisor_id'), table_name='virtual_machines')
    op.drop_index(op.f('ix_virtual_machines_openshift_vm_name'), table_name='virtual_machines')
    op.drop_index(op.f('ix_virtual_machines_name'), table_name='virtual_machines')
    op.drop_index(op.f('ix_virtual_machines_id'), table_name='virtual_machines')
    op.drop_index(op.f('ix_virtual_machines_compatibility_status'), table_name='virtual_machines')
    op.drop_table('virtual_machines')
    op.drop_index(op.f('ix_hypervisors_type'), table_name='hypervisors')
    op.drop_index(op.f('ix_hypervisors_status'), table_name='hypervisors')
    op.drop_index(op.f('ix_hypervisors_name'), table_name='hypervisors')
    op.drop_index(op.f('ix_hypervisors_id'), table_name='hypervisors')
    op.drop_table('hypervisors')
    # ### end Alembic commands ###
